#!/usr/bin/env sh

NAME=$(jl package.json name)
MAJOR=$(./version.js major)
MINOR=$(./version.js minor)
PATCH=$(./version.js patch)

docker build --no-cache \
  -t "$NAME:latest" \
  -t "$NAME:$PATCH" \
  -t "$NAME:$MINOR" \
  -t "$NAME:$MAJOR" .

docker tag "$NAME:latest" "bigslycat/$NAME:latest"
docker tag "$NAME:$PATCH" "bigslycat/$NAME:$PATCH"
docker tag "$NAME:$MINOR" "bigslycat/$NAME:$MINOR"
docker tag "$NAME:$MAJOR" "bigslycat/$NAME:$MAJOR"

docker push "bigslycat/$NAME:latest"
docker push "bigslycat/$NAME:$PATCH"
docker push "bigslycat/$NAME:$MINOR"
docker push "bigslycat/$NAME:$MAJOR"
